plugins:
  - jekyll-assets
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-gist
  - jekyll/scholar
  - jekyll-seo-tag
  - jekyll-sitemap
  - pandoc-ruby
include:
  - .well-known
  - _headers
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - node_modules
  - package.json
  - vendor
  - yarn.lock

name: CHENG XU
url: https://xuc.me
disqus: xuc
google_analytics: UA-4293090-10

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:title/

nav:
  - title: home
    url: /
  - title: blog
    url: /blog/

contact:
  email: chengxu@comp.hkbu.edu.hk
  gpg: /.well-known/pgp_keys.asc
  github: https://github.com/xu-cheng
  twitter: https://twitter.com/_xucheng_

# jekyll-assets config
assets:
  digest: false
  sources:
    - node_modules
  raw_precompile:
    - src: font-awesome/fonts/*
      dst: fonts
    - src: katex/dist/fonts/*
      dst: fonts
    - photo.jpg
    - photo@2x.jpg
# jekyll-feed config
feed:
  path: blog.xml
# jekyll-scholar config
scholar:
  bibliography: publications
  style: ieee
  sort_by: year,month,day
  order: descending
  bibliography_list_tag: ul
  bibtex_filters: pandoc
  use_raw_bibtex_entry: false
  bibtex_skip_fields:
    - abstract
    - author+an
    - month_numeric
    - note
    - poster
    - preprint
    - slides
    - url
# jekyll-seo-tag config
twitter:
  username: _xucheng_
