gems:
  - jemoji
  - jekyll-archives
  - jekyll-assets
  - jekyll-coffeescript
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll/scholar
  - jekyll-seo-tag
  - jekyll-sitemap
include:
  - .well-known
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - bower.json
  - bower_components
  - node_modules
  - package.json
  - vendor

name: XU CHENG
url: https://xuc.me
disqus: xuc
google_analytics: UA-4293090-10

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:title/

nav:
  - title: home
    url: /
  - title: blog
    url: /blog/

contact:
  email: chengxu@comp.hkbu.edu.hk
  gpg: https://keybase.io/xucheng/pgp_keys.asc
  github: https://github.com/xu-cheng
  twitter: https://twitter.com/_xucheng_

# jekyll-archives config
jekyll-archives:
  enabled: []
# jekyll-assets config
assets:
  assets:
    - "fonts/*"
  digest: false
  features:
    integrity: true
  sources:
    - bower_components/font-awesome
    - bower_components/katex/dist
    - bower_components
# jekyll-feed config
feed:
  path: blog.xml
# jekyll-seo-tag config
twitter:
  username: _xucheng_
