gems:
  - jemoji
  - jekyll-archives
  - jekyll-assets
  - jekyll-coffeescript
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll/scholar
  - jekyll-seo-tag
  - jekyll-sitemap
include:
  - .well-known
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - bower.json
  - bower_components
  - node_modules
  - package.json
  - vendor

name: XU CHENG
url: https://xuc.me
github:
  username: xu-cheng
twitter:
  username: _xucheng_
disqus: xuc
google_analytics: UA-4293090-10

permalink: /blog/:title/

nav:
  - title: home
    url: /
  - title: blog
    url: /blog/
  - title: contact
    url: /contact/

# jekyll-assets config
assets:
  assets:
    - "fonts/*"
  sources:
    - bower_components/font-awesome
    - bower_components/katex/dist
    - bower_components
# jekyll-feed config
feed:
  path: blog.xml
