plugins:
  - jekyll-assets
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/scholar
include:
  - .well-known
  - _headers
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - netlify.toml
  - node_modules
  - package.json
  - vendor
  - yarn.lock

name: CHENG XU
url: https://xuc.me
disqus: xuc
google_analytics: UA-4293090-10

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:slug/

nav:
  - title: home
    url: /
    active_regex: '^/$'
  - title: blog
    url: /blog/
    active_regex: '^/blog/.*$'
  - title: CV
    url: /file/cv.pdf

contact:
  email: chengxu@comp.hkbu.edu.hk
  gpg: /.well-known/pgp_keys.asc
  github: https://github.com/xu-cheng
  linkedin: https://linkedin.com/in/xu-cheng
  twitter: https://twitter.com/_xucheng_

# jekyll-assets config
assets:
  digest: false
  sources:
    - node_modules
  raw_precompile:
    - src: roboto-*.woff
      dst: fonts
    - src: roboto-*.woff2
      dst: fonts
    - src: font-awesome/fonts/*
      dst: fonts
    - src: katex/dist/fonts/*
      dst: fonts
    - photo.jpg
    - photo@2x.jpg
# jekyll-feed config
feed:
  path: blog.xml
# jekyll-scholar config
scholar:
  bibliography: publications
  style: ieee
  sort_by: year,month,day
  order: descending
  bibliography_list_tag: ul
  bibtex_filters: pandoc
  bibtex_skip_fields:
    - abstract
    - addendum
    - author+an
    - eprint_url
    - month_numeric
    - poster_url
    - slides_url
    - url
# jekyll-seo-tag config
twitter:
  username: _xucheng_
social:
  name: Cheng Xu
  links:
    - https://twitter.com/_xucheng_
    - https://www.linkedin.com/in/xu-cheng
    - https://github.com/xu-cheng
    - https://keybase.io/xucheng
webmaster_verifications:
  google: Wv-QPWOMpVz05kAMZf2O-BNmHE609G9uW2kdAmKoIsI

