name: auto-merge
on: pull_request_target
jobs:
  check:
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - run: pip install semver
      - id: check
        run: |
          from semver import VersionInfo
          import re

          title = "${{ github.event.pull_request.title }}"
          match = re.match(r"^.* from ([\w\.]+) to ([\w\.]+)$", title)
          from_version = VersionInfo.parse(match.group(1))
          to_version = VersionInfo.parse(match.group(2))
          print(f"version info: {from_version} -> {to_version}")
          if from_version.major == to_version.major and (from_version.major > 0 or from_version.minor == to_version.minor):
              print("::set-output name=result::pass")
        shell: python

  auto-merge:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: check
    steps:
      - if: needs.check.outputs.result == 'pass'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
